baseURL: "https://hansproject.netlify.app"
languageCode: "en-us"
title: "Han's Project"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: portfolio
      name: Portfolio
      title: Data Analytics Projects
      url: /projects
      weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Han's Project"
  description: Muhammad Shalhan Assalam's Project Showcase
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav1.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Han's Project" # Brand name for the brand | default is the title variable
    disableSearch: false
    searchPlaceholder: "Search my projects"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hola, I'm"
    title: "Shalhan."
    subtitle: "Crafting Data Narratives for Informed Decision Making"
    content: "I'm Shalhan, a data wizard on a quest to reveal the stories hidden in numbers. Armed with analytical sorcery, I unravel data's mysteries, crafting actionable insights for informed decisions. Join me in this data-driven journey to transform information into wisdom."
    image: /images/me2.jpeg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "https://drive.google.com/file/d/1zKSCtk6ymkfW_Guknwnbu92BV8k6MzHu/view?usp=sharing"
      download: false
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/muhshalhan
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/muhammad-shalhan-assalam-b42973200/
      customIcons:
        - icon: /images/tableau-icon.svg
          url: "https://public.tableau.com/app/profile/muhammad.shalhan.assalam"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me1.png"
    content: |-
      Hello, I'm Muhammad Shalhan Assalam, a hard-working and dedicated data analyst who is passionate about uncovering insights through deep analysis of details.

      I’ve worked in various economic research and business projects handling end-to-end data analysis projects. I gained valuable experience in generating high-quality insight and recommendations both from academic and business perspectives.

      My strong experience in data-driven economics and business, ignited my passion for data, leading me to accomplish the Full Stack Data Analytics program at RevoU. I’m proficient in conducting end-to-end data analysis using Spreadsheets, SQL, Python, Tableau, and Looker Studio, accompanied by strong analytical thinking, problem-solving abilities, and effective communication capabilities.

      With a solid foundation of skills and experience, I believe I can be a valuable data analyst to support your company’s data analytics project. Currently, I'm open to any work opportunities, especially as Business Intelligence, Data Analyst, or Data Engineer. Feel free to send a message to my LinkedIn profile or mail to muh.shalhan@gmail.com
    skills:
      enable: true
      title: "Here are a few tools and technique I've been working recently:"
      items:
        - "Python (Pandas, Numpy, Seaborn, Scikitlearn)"
        - "SQL (BigQuery, PostgreSQL)"
        - "Tabelau & Looker Studio"
        - "Data Analysis (Exploratory Data Analysis, Exploratory Data Visualization)" 
        - "Statistical Modelling (Cross-section, Time-series, Panel, Prospensity Model)"
        - "Statistical Software (STATA, EVIEWS)"
        - "Soft Skills: Analytical Thinking, Attention to Detail, Communication"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Data Analyst Associate"
        company: "RevoU"
        companyUrl: "https://Revou.co"
        date: "Sep 2023 - present"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        content: "Apprenticeship with project based learning for accelerating my Data Analyst career."

      - job: "Assistant Research and Lecturer"
        company: "Airlangga university"
        companyUrl: "https://unair.ac.id"
        date: "Dec 2021 - Present"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: true
          content: I worked as research and teaching assistant in Airlangga University.
        content: |
          Activities:

          1. Teached 100+ undergraduate and postgraduate students in Islamic Economic Department for Econometrics Subject.
          2. Arranged 8 chapters of Econometrics subject notes and exercises for OLS Regression, Binary Regression, Time Series, and Panel Regression.
          3. Assisted and designed research methodology for the Early Warning System Banking Crisis Research Project.
          4. Collected and cleaned 100 data of respondents as data enumerators in a national research program with National Islamic Economy and Finance Committee (KNEKS)
          5. Arranged Islamic Microfinance Deposit Insurance Report Research 2021 in collaboration with National Islamic Economy and Finance Committee (KNEKS)
          6. Arranged 9 chapter material textbook in Asset and Liability Management (ALM) subject for five years plan syllabus.

      - job: "Assistant Banking Consulting"
        company: "BSMR Consulting"
        companyUrl: ""
        date: "Jun 2021 - May 2022"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          Activities:

          1. Analyzed economic and socio-demographical data and provided sharia banking conversion business prospect reports for Kaltimtara's Bank.
          2. Created infographics from 70+ economic data for Kaltimtara's Sharia bank conversion prospect report.
          3. Provided and cleaned 180+ economic data for Riau Kepri's Sharia Banking conversion prospect report.
          4. Created banking risk management infographics for Riau Kepri Bank.
          5. Arranged an eye-catching roadmap presentation of Bank Riau Kepri's conversion to Sharia Bank for the Board of Directors.

      #- job: "UI/UX Designer"
      #  company: "Netflix"
      #  companyUrl: "https://example.com"
      #  date: "June 2017 - Nov 2019"
      #  featuredLink:
      #    enable: true
      #    url: "https://example.com"
      #  content: |
      #    I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

      #    - Lead backend developer for a product.
      #    - Created a frontend design for a product.

      #- job: "Product Designer"
      #  company: "Google"
      #  companyUrl: "https://example.com"
      #  date: "Feb 2016 - Mar 2017"
      #  content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Fullstack Data Analyst RevoU Batch 6 2023"
        school:
          name: "RevoU"
          url: "https://revou.co"
        date: "May 2023 - Sep 2023"
        GPA: "98 out of 100"
        content: |-
          Learning Activities:
            1. Understanding business problem using root cause analysis, DARCI framework, and hypothesis making to arrive data-driven solutions.
            2. Statistical analysis skills including hypothesis testing, regression modeling, using spreadsheets.
            3. Data processing across the pipeline - extracting, cleaning, analyzing, visualizing and modeling data.
            4. Data storytelling through building compelling visualizations and dashboards to communicate insights.
      - title: "Bachelor of Islamic Economics"
        school:
          name: "Airlangga University"
          url: "https://unair.ac.id"
        date: "August 2018 - July 2022"
        GPA: "3.95 out of 4.00"
        content: |-
          Learning Activities:
            1. Understanding business problem using root cause analysis, DARCI framework, and hypothesis making to arrive data-driven solutions.
            2. Statistical analysis skills including hypothesis testing, regression modeling, using spreadsheets.
            3. Data processing across the pipeline - extracting, cleaning, analyzing, visualizing and modeling data.
            4. Data storytelling through building compelling visualizations and dashboards to communicate insights.
        school:
          name: "Airlangga University"
          url: "https://unair.ac.id"
        date: "2018 - 2022"
        GPA: "3.95 out of 4.0"
        content: |-
          My thesis title:
          "STABILITY AND CAUSALITY OF ISLAMIC AND CONVENTIONAL STOCK MARKETS IN DEVELOPED, EMERGING, AND FRONTIER MARKETS RESPONDING TO COVID-19 PANDEMIC"

          Extracurricular Activities
            - Lecturer and Research Assistant. 
            - Member of several Islamic Economics research organization 
        featuredLink:
          enable: false
          name: "My academic record"
          url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: Best Student FSDA Section Seoul Batch 6 RevoU 2023
        content: I solved all problems with optimal solution.
        #url: https://example.com
        image: /images/achievment.jpg
      - title: Python Competition Winner Section Seoul Batch 6 RevoU 2023
        content: Developed a product using Artificial Intelligence.
        image: /images/achievment.jpg
      #- title: Best Graduate 
      #  content: Developed a theme and getting 1K+ downloads per month.
      #  url: "https://github.com/gurusabarish/hugo-profile"
      #  image: /images/achievment.jpg
      #- title: Microsoft Imagine Runner
      #  content: We are developed a product which can help others.
      #- title: Google Summer of Code
      #  content: Contributed to a open source project.
      #  url: https://example.com

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    # items:
    #   - title: Hugo Profile
    #     content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
    #     image: /images/projects/profile.png
    #     featured:
    #       name: Demo
    #       link: https://hugo-profile.netlify.app
    #     badges:
    #       - "Hugo"
    #       - "Bootstrap"
    #       - "Javascript"
    #     links:
    #       - icon: fa fa-envelope
    #         url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
    #       - icon: fab fa-github
    #         url: https://github.com/gurusabarish/hugo-profile
    #       - icon: fab fa-twitter
    #         url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

    #   - title: Image Converter
    #     content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
    #     image: /images/projects/converter.jpg
    #     featured:
    #       name: Demo
    #       link: https://django-converter.herokuapp.com
    #     badges:
    #       - "Django"
    #       - "Bootstrap"
    #     links:
    #       - icon: fab fa-github
    #         url: https://github.com/gurusabarish/converter

    #   - title: Hugo Profile V2
    #     content: A clean and simple Hugo template for personal portfolio and blog.
    #     image: /images/projects/profile2.jpg
    #     featured:
    #       name: Demo V2
    #       link: https://hugo-profile-2.netlify.app
    #     badges:
    #       - "Hugo"
    #       - "Bootstrap"
    #       - "Javascript"
    #     links:
    #       - icon: fab fa-github
    #         url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: muh.shalhan@gmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/muhshalhan
      linkedin: https://www.linkedin.com/in/muhammad-shalhan-assalam-b42973200/
      #twitter: https://twitter.com
      instagram: https://www.instagram.com/muh.shalhan/
      #facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
